spring:
  application:
    name: InterviewSys
  profiles:
    active: prod
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
